[package]
name = "lesson_files"
version = "0.1.0"
authors = ["Sky020 <2397860h@student.gla.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
